In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 数组的运算
使用 NumPy 最为方便的是当需要对数组元素进行运算时，不用编写循环代码遍历每个元素，所有的运算都会自动的矢量化。简单的说就是，NumPy 中的数学运算和数学函数会自动作用于数组中的每个成员。

#### 数组跟标量的运算
NumPy 的数组可以跟一个数值进行加、减、乘、除、求模、求幂等运算，对应的运算会作用到数组的每一个元素上，如下所示。

In [9]:
array1 = np.arange(1, 10)
print("array1:")
print(array1)
print("array1 + 10:")
print(array1 + 10)
print("array1 * 10:")
print(array1 * 10)

array1:
[1 2 3 4 5 6 7 8 9]
array1 + 10:
[11 12 13 14 15 16 17 18 19]
array1 * 10:
[10 20 30 40 50 60 70 80 90]


除了上述的运算，关系运算也是没有问题的，之前讲布尔索引的时候已经遇到过了。

In [10]:
print(array1 > 5)
print(array1 % 2 == 0)

[False False False False False  True  True  True  True]
[False  True False  True False  True False  True False]


#### 数组跟数组的运算

NumPy 的数组跟数组也可以执行算术运算和关系运算，运算会作用于两个数组对应的元素上，这就要求两个数组的形状（shape属性）要相同，如下所示。

In [11]:
array2 = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
print(array1 + array2)
print(array1 * array2)
print(array1 ** array2)

[ 2  3  4  6  7  8 10 11 12]
[ 1  2  3  8 10 12 21 24 27]
[  1   2   3  16  25  36 343 512 729]


In [12]:
print(array1 > array2)
print(array1 % array2 == 0)

[False  True  True  True  True  True  True  True  True]
[ True  True  True  True False  True False False  True]


### 通用一元函数

NumPy 中通用一元函数的参数是一个数组对象，函数会对数组进行元素级的处理，例如：sqrt函数会对数组中的每个元素计算平方根，而log2函数会对数组中的每个元素计算以2为底的对数，代码如下所示。

In [13]:
print(np.sqrt(array1))
print(np.log2(array1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


#### 通用二元函数

NumPy 中通用二元函数的参数是两个数组对象，函数会对两个数组中的对应元素进行运算，例如：maximum函数会对两个数组中对应的元素找最大值，而power函数会对两个数组中对应的元素进行求幂操作，代码如下所示。

In [14]:
array3 = np.array([[4, 5, 6], [7, 8, 9]])
array4 = np.array([[1, 2, 3], [3, 2, 1]])
print(np.maximum(array3, array4))
print(np.power(array3, array4))

[[4 5 6]
 [7 8 9]]
[[  4  25 216]
 [343  64   9]]


#### 广播机制

上面数组运算的例子中，两个数组的形状（shape属性）是完全相同的，我们再来研究一下，两个形状不同的数组是否可以直接做二元运算或使用通用二元函数进行运算，请看下面的例子。

In [15]:
array5 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array6 = np.array([1, 2, 3])
array5 + array6

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [16]:
array7 = np.array([[1], [2], [3], [4]])
array5 + array7

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

通过上面的例子，我们发现形状不同的数组仍然有机会进行二元运算，但这不代表任意形状的数组都可以进行二元运算。简单的说，只有两个数组后缘维度相同或者后缘维度不同但其中一个数组后缘维度为1时，广播机制才会被触发。通过广播机制，NumPy 将两个原本形状不相同的数组变成形状相同，才能进行二元运算。所谓后缘维度，指的是数组形状（shape属性）从后往前看对应的部分，我们举例说明。

### 其他常用函数

除了上面讲到的函数外，NumPy 中还提供了很多用于处理数组的函数，ndarray对象的很多方法也可以通过调用函数来实现，下表给出了一些常用的函数。

In [17]:
np.unique(array5)

array([0, 1, 2, 3])

堆叠和拼接。

In [18]:
array8 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array9 = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])
np.hstack((array8, array9))

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])

In [19]:
np.vstack((array8, array9))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [20]:
np.concatenate((array8, array9))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [21]:
np.concatenate((array8, array9), axis=1)

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])

追加和插入元素。

In [22]:
np.append(array1, [10, 100])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [23]:
np.insert(array1, 1, [98, 99, 100])

array([  1,  98,  99, 100,   2,   3,   4,   5,   6,   7,   8,   9])

抽取和处理元素。

In [24]:
np.extract(array1 % 2 != 0, array1)

array([1, 3, 5, 7, 9])

In [25]:
np.select([array1 <= 3, array1 >= 7], [array1 * 10, array1 ** 2])

array([10, 20, 30,  0,  0,  0, 49, 64, 81])

In [26]:
np.where(array1 <= 5, array1 * 10, array1 ** 2)

array([10, 20, 30, 40, 50, 36, 49, 64, 81])

重复数组元素创建新数组。

In [27]:
np.repeat(array1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9])

In [28]:
np.tile(array1, 2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

调整数组大小。

In [29]:
np.resize(array1, (5, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
np.resize(array5, (2, 4))

array([[0, 0, 0, 1],
       [1, 1, 2, 2]])

替换数组元素。

In [31]:
np.put(array1, [0, 1, -1, 3, 5], [100, 200])
array1

array([100, 200,   3, 200,   5, 100,   7,   8, 100])

In [32]:
np.place(array1, array1 > 5, [1, 2, 3])
array1

array([1, 2, 3, 3, 5, 1, 2, 3, 1])