### 正规方程使用

In [1]:
import numpy as np

In [6]:
X = np.array([[1,1],[2,-1]])
X

array([[ 1,  1],
       [ 2, -1]])

In [4]:
y = np.array([14, 10])
y

array([14, 10])

In [5]:
# linalg 线性代数，slove计算先行回归问题
np.linalg.solve(x,y)

array([8., 6.])

$$ f(x,y)=8x +6y

$$ W = (X^TX)^{-1}X^Ty

In [10]:
# X转制
X.T
# 矩阵运算
A = X.T.dot(X)
# 逆矩阵计算
B = np.linalg.inv(A)
C = B.dot(X.T)
C.dot(y)

array([8., 6.])

#### 三元一次方程

In [11]:
X = np.array([[1, -1, 1], [2, 1, -1], [3, -2, 6]])
X

array([[ 1, -1,  1],
       [ 2,  1, -1],
       [ 3, -2,  6]])

In [12]:
y = np.array([100, 80, 256])
y

array([100,  80, 256])

In [19]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([ 60., -41.,  -1.])

### sklearn算法使用

In [13]:
# linear线性，model模型、算法
# LinearRegression：线性回归
from sklearn.linear_model import LinearRegression

In [17]:
model = LinearRegression(fit_intercept=False)
# fit_intercept=False不计算截距

# X 数据； y 目标值
display(X,y)
model.fit(X,y)
# coef_ 结果，返回值，斜率，系数，方程的解
model.coef_

array([[ 1, -1,  1],
       [ 2,  1, -1],
       [ 3, -2,  6]])

array([100,  80, 256])

array([ 60., -41.,  -1.])

### 带截距的线性方程